spring:
  application:
    name: learner-product-api
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #    password: ****
    #    url
    password: root
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    #    password: **** JAVA_OPTS=-Dspring.profile="test"
    #    url
    password: Gcp@2023 # 100% ,ciphers ===>  devs will encrypt this usig spring
    url: jdbc:mysql://35.224.187.49:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8132
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.16.196.228:5761/eureka/
---
